"""
lazily — a lazy/reactive evaluation library for Python with context-aware
callable wrappers.

This package provides a simple and elegant way to implement lazy evaluation and
dependency injection patterns in Python applications. The core reactive family is
``Slot`` (lazy memo) → ``Cell`` (mutable source) → ``Signal`` (eager derived).

The :mod:`lazily.ipc` submodule implements the language-agnostic ``lazily-spec``
wire protocol (Snapshot / Delta) so a Python graph's state can be mirrored to
remote observers across processes and languages.
"""

__all__ = [
    "ANCHOR_PREFIX",
    "ARROW_DEFAULT_CAPACITY",
    "CONTENT_PREFIX",
    "FFI_HEADER_LEN",
    "IN_PROCESS_DEFAULT_CAPACITY",
    "NODE_KEY_MAX_LEN",
    "NODE_KEY_MAX_SEGMENTS",
    "PROTOCOL_ID",
    "PROTOCOL_MAJOR_VERSION",
    "ROOT",
    "SHM_BLOB_HEADER_LEN",
    "SHM_DEFAULT_CAPACITY",
    "Alignment",
    "ArrowBackend",
    "AsyncCellMap",
    "AsyncEffect",
    "AsyncReactiveMap",
    "AsyncSlot",
    "AsyncSlotMap",
    "BackpressurePolicy",
    "BaseSlot",
    "Benchmark",
    "BenchmarkResult",
    "BlobBackend",
    "BlobBackendKind",
    "BlobRouter",
    "BlobView",
    "BoundDim",
    "CallState",
    "CallStateKind",
    "CapabilityHandshake",
    "CausalReceipt",
    "CausalReceipts",
    "Cell",
    "CellCrdt",
    "CellMap",
    "CellSlot",
    "CellTree",
    "ChartDef",
    "Clock",
    "CommandApplyStatus",
    "CommandCancel",
    "CommandEvent",
    "CommandEventKind",
    "CommandEvents",
    "CommandMessage",
    "CommandPolicy",
    "CommandProjection",
    "CommandProjectionEntry",
    "CommandProjectionImage",
    "CommandRpcClient",
    "CommandStatus",
    "CommandSubmit",
    "CommandTransport",
    "CrdtOp",
    "CrdtPlaneRuntime",
    "CrdtSync",
    "DedupePolicy",
    "Delta",
    "DeltaApplyStatus",
    "DeltaOp",
    "DriverError",
    "DurableOutbox",
    "EdgeSnapshot",
    "Effect",
    "EffectEvent",
    "EffectState",
    "EntryKind",
    "ExpiryPolicy",
    "Fold",
    "FramedTransport",
    "InMemoryOutbox",
    "InProcTransport",
    "InProcessBackend",
    "Inbox",
    "IngressOutcome",
    "IpcMessage",
    "IpcValue",
    "KeepLatest",
    "KeyedRelay",
    "LazilyCallable",
    "LazilyFfiBytes",
    "LazilyFfiMessageKind",
    "LazilyFfiStatus",
    "LeafKind",
    "Level",
    "LosslessTreeCrdt",
    "LwwRegister",
    "Max",
    "MergeCell",
    "MergePolicy",
    "MvRegister",
    "NodeId",
    "NodeKey",
    "NodeKeyError",
    "NodeSeed",
    "NodeSnapshot",
    "NodeState",
    "OpId",
    "OpKind",
    "OrSet",
    "Outbox",
    "OutboxAck",
    "Overflow",
    "PeerId",
    "PeerPermissions",
    "PermissionDenied",
    "PermissionMode",
    "PlaneEntry",
    "PnCounter",
    "PriorityStorage",
    "Progress",
    "QueueCell",
    "QueuePopError",
    "QueuePushError",
    "QueueReaderHandles",
    "QueueStorage",
    "RatePolicy",
    "RawFifo",
    "ReactiveMap",
    "ReceiptApplyResult",
    "ReceiptOutcome",
    "ReceiptProjection",
    "ReconcileOp",
    "RelayCell",
    "RelayConfigError",
    "RemoteOp",
    "ResyncAction",
    "ResyncActionKind",
    "ResyncCoordinator",
    "ResyncRequest",
    "RoomCore",
    "RoomError",
    "SeedElement",
    "SeedLeaf",
    "SemNode",
    "SemTree",
    "SeqCrdt",
    "SeqElement",
    "SetUnion",
    "ShmBackend",
    "ShmBlobArena",
    "ShmBlobArenaError",
    "ShmBlobRef",
    "Signal",
    "SignalingFrame",
    "SignalingFrameKind",
    "Slot",
    "SlotEvent",
    "SlotMap",
    "SlotState",
    "Snapshot",
    "SnapshotProvider",
    "SortKey",
    "SpillMode",
    "SpillPage",
    "SpillStore",
    "StaleGeneration",
    "StateChart",
    "StateMachine",
    "StateMirror",
    "Sum",
    "SyncDriver",
    "TerminalConflict",
    "TextCrdt",
    "TextElement",
    "TextOp",
    "ThreadSafeCellMap",
    "ThreadSafeContext",
    "ThreadSafeReactiveMap",
    "ThreadSafeSlotMap",
    "Transport",
    "TreeError",
    "TreeNode",
    "TreeNodeId",
    "TreeOp",
    "TreeOpId",
    "TreeUpdate",
    "TreeVersionFrontier",
    "VecDequeStorage",
    "WindowPolicy",
    "WireLwwRegister",
    "WireStamp",
    "align",
    "applied_receipt",
    "assign_stable_keys",
    "async_reactive_family",
    "async_slot",
    "batch",
    "batch_context",
    "benchmarks",
    "block_key",
    "byte_to_char",
    "cell",
    "cell_def",
    "command",
    "content_hash",
    "count_positive_fold",
    "crdt_plane",
    "crdt_registers",
    "decode_message",
    "effect",
    "encode_message",
    "ffi",
    "ffi_bytes_of",
    "in_batch",
    "ipc",
    "key_between",
    "kind_of",
    "lossless_tree_crdt",
    "merge_cell",
    "normalize_ws",
    "projection",
    "queue",
    "reconcile_ops",
    "rejected_receipt",
    "reliable_sync",
    "resolve_value",
    "run_benchmarks",
    "seqcrdt",
    "signal",
    "signal_def",
    "signaling",
    "similarity",
    "slot",
    "slot_def",
    "spill_message",
    "spill_state",
    "spill_value",
    "stable_id",
    "sum_fold",
    "textcrdt",
    "thread_safe_reactive_family",
    "tree",
    "tree_update_from_wire",
    "tree_update_to_wire",
    "word_lcs_len",
]
__version__ = "0.26.0"

from . import (
    async_reactive_family,
    async_slot,
    benchmarks,
    command,
    crdt_plane,
    crdt_registers,
    ffi,
    ipc,
    lossless_tree_crdt,
    projection,
    queue,
    reliable_sync,
    seqcrdt,
    signaling,
    stable_id,
    textcrdt,
    thread_safe_reactive_family,
    tree,
)
from .async_effect import AsyncEffect, EffectEvent, EffectState
from .async_reactive_family import AsyncCellMap, AsyncReactiveMap, AsyncSlotMap
from .async_slot import AsyncSlot, SlotEvent, SlotState
from .batch import batch, batch_context, in_batch
from .benchmarks import Benchmark, BenchmarkResult, run_benchmarks
from .cell import Cell, CellSlot, cell, cell_def
from .collection import CellMap, EntryKind, ReactiveMap, SlotMap
from .command import (
    COMMAND_PLANE_FEATURE,
    CallState,
    CallStateKind,
    CommandApplyStatus,
    CommandCancel,
    CommandEvent,
    CommandEventKind,
    CommandEvents,
    CommandMessage,
    CommandPolicy,
    CommandProjection,
    CommandProjectionEntry,
    CommandProjectionImage,
    CommandRpcClient,
    CommandStatus,
    CommandSubmit,
    CommandTransport,
    DedupePolicy,
    StaleGeneration,
    TerminalConflict,
    applied_receipt,
    rejected_receipt,
)
from .crdt_plane import CrdtPlaneRuntime, PlaneEntry
from .crdt_registers import CellCrdt, LwwRegister, MvRegister, PnCounter
from .effect import Effect, effect
from .ffi import (
    FFI_HEADER_LEN,
    LazilyFfiBytes,
    LazilyFfiMessageKind,
    LazilyFfiStatus,
    decode_message,
    encode_message,
    ffi_bytes_of,
    kind_of,
)
from .ipc import (
    NODE_KEY_MAX_LEN,
    NODE_KEY_MAX_SEGMENTS,
    PROTOCOL_ID,
    PROTOCOL_MAJOR_VERSION,
    SHM_BLOB_HEADER_LEN,
    BlobBackendKind,
    CapabilityHandshake,
    CausalReceipt,
    CausalReceipts,
    CrdtOp,
    CrdtSync,
    Delta,
    DeltaApplyStatus,
    DeltaOp,
    EdgeSnapshot,
    IpcMessage,
    IpcValue,
    NodeId,
    NodeKey,
    NodeKeyError,
    NodeSnapshot,
    NodeState,
    OpKind,
    OutboxAck,
    PeerId,
    PeerPermissions,
    PermissionDenied,
    ReceiptApplyResult,
    ReceiptOutcome,
    ReceiptProjection,
    RemoteOp,
    ResyncRequest,
    ShmBlobArena,
    ShmBlobArenaError,
    ShmBlobRef,
    Snapshot,
    WireStamp,
)
from .lossless_tree_crdt import (
    LeafKind,
    LosslessTreeCrdt,
    NodeSeed,
    SeedElement,
    SeedLeaf,
    SortKey,
    TreeError,
    TreeNodeId,
    TreeOp,
    TreeOpId,
    TreeUpdate,
    TreeVersionFrontier,
    byte_to_char,
    key_between,
    tree_update_from_wire,
    tree_update_to_wire,
)
from .merge import (
    KeepLatest,
    Max,
    MergeCell,
    MergePolicy,
    RawFifo,
    SetUnion,
    Sum,
    merge_cell,
)
from .projection import StateMirror
from .queue import (
    QueueCell,
    QueuePopError,
    QueuePushError,
    QueueReaderHandles,
    QueueStorage,
    VecDequeStorage,
)
from .reconciliation import Level, ReconcileOp, reconcile_ops
from .relay import (
    BackpressurePolicy,
    BoundDim,
    ExpiryPolicy,
    FramedTransport,
    Inbox,
    IngressOutcome,
    InProcTransport,
    KeyedRelay,
    Outbox,
    Overflow,
    PriorityStorage,
    RatePolicy,
    RelayCell,
    RelayConfigError,
    SpillMode,
    SpillPage,
    SpillStore,
    Transport,
    WindowPolicy,
)
from .reliable_sync import (
    Clock,
    DriverError,
    DurableOutbox,
    InMemoryOutbox,
    OrSet,
    Progress,
    ResyncAction,
    ResyncActionKind,
    ResyncCoordinator,
    SnapshotProvider,
    SyncDriver,
    WireLwwRegister,
)
from .semtree import Fold, SemNode, SemTree, count_positive_fold, sum_fold
from .seqcrdt import SeqCrdt, SeqElement
from .signal import Signal, signal, signal_def
from .signaling import (
    PermissionMode,
    RoomCore,
    RoomError,
    SignalingFrame,
    SignalingFrameKind,
)
from .slot import BaseSlot, Slot, slot, slot_def
from .stable_id import (
    ANCHOR_PREFIX,
    CONTENT_PREFIX,
    Alignment,
    align,
    assign_stable_keys,
    block_key,
    content_hash,
    normalize_ws,
    similarity,
    word_lcs_len,
)
from .state_machine import StateMachine
from .statechart import ChartDef, StateChart
from .textcrdt import ROOT, OpId, TextCrdt, TextElement, TextOp
from .thread_safe import ThreadSafeContext
from .thread_safe_reactive_family import (
    ThreadSafeCellMap,
    ThreadSafeReactiveMap,
    ThreadSafeSlotMap,
)
from .transport import (
    ARROW_DEFAULT_CAPACITY,
    IN_PROCESS_DEFAULT_CAPACITY,
    SHM_DEFAULT_CAPACITY,
    ArrowBackend,
    BlobBackend,
    BlobRouter,
    BlobView,
    InProcessBackend,
    ShmBackend,
    resolve_value,
    spill_message,
    spill_state,
    spill_value,
)
from .tree import CellTree, TreeNode
from .types import LazilyCallable
