"""
lazily — a lazy/reactive evaluation library for Python with context-aware
callable wrappers.

This package provides a simple and elegant way to implement lazy evaluation and
dependency injection patterns in Python applications. The core reactive family is
``Slot`` (lazy memo) → ``Cell`` (mutable source) → ``Signal`` (eager derived).

The :mod:`lazily.ipc` submodule implements the language-agnostic ``lazily-spec``
wire protocol (Snapshot / Delta) so a Python graph's state can be mirrored to
remote observers across processes and languages.
"""

__all__ = [
    "ANCHOR_PREFIX",
    "CONTENT_PREFIX",
    "FFI_HEADER_LEN",
    "NODE_KEY_MAX_LEN",
    "NODE_KEY_MAX_SEGMENTS",
    "PROTOCOL_ID",
    "PROTOCOL_MAJOR_VERSION",
    "ROOT",
    "SHM_BLOB_HEADER_LEN",
    "Alignment",
    "AsyncEffect",
    "AsyncSlot",
    "BaseSlot",
    "Benchmark",
    "BenchmarkResult",
    "CallState",
    "CallStateKind",
    "CapabilityHandshake",
    "CausalReceipt",
    "CausalReceipts",
    "Cell",
    "CellCrdt",
    "CellFamily",
    "CellMap",
    "CellSlot",
    "CellTree",
    "ChartDef",
    "CommandApplyStatus",
    "CommandCancel",
    "CommandEvent",
    "CommandEventKind",
    "CommandEvents",
    "CommandMessage",
    "CommandPolicy",
    "CommandProjection",
    "CommandProjectionEntry",
    "CommandProjectionImage",
    "CommandRpcClient",
    "CommandStatus",
    "CommandSubmit",
    "CommandTransport",
    "CrdtOp",
    "CrdtPlaneRuntime",
    "CrdtSync",
    "DedupePolicy",
    "Delta",
    "DeltaApplyStatus",
    "DeltaOp",
    "EdgeSnapshot",
    "Effect",
    "EffectEvent",
    "EffectState",
    "Fold",
    "IpcMessage",
    "IpcValue",
    "LazilyCallable",
    "LazilyFfiBytes",
    "LazilyFfiMessageKind",
    "LazilyFfiStatus",
    "LeafKind",
    "Level",
    "LosslessTreeCrdt",
    "LwwRegister",
    "MvRegister",
    "NodeId",
    "NodeKey",
    "NodeKeyError",
    "NodeSeed",
    "NodeSnapshot",
    "NodeState",
    "OpId",
    "OpKind",
    "PeerId",
    "PeerPermissions",
    "PermissionDenied",
    "PermissionMode",
    "PlaneEntry",
    "PnCounter",
    "ReceiptApplyResult",
    "ReceiptOutcome",
    "ReceiptProjection",
    "ReconcileOp",
    "RemoteOp",
    "RoomCore",
    "RoomError",
    "SeedElement",
    "SeedLeaf",
    "SemNode",
    "SemTree",
    "SeqCrdt",
    "SeqElement",
    "ShmBlobArena",
    "ShmBlobArenaError",
    "ShmBlobRef",
    "Signal",
    "SignalingFrame",
    "SignalingFrameKind",
    "Slot",
    "SlotEvent",
    "SlotState",
    "Snapshot",
    "SortKey",
    "StaleGeneration",
    "StateChart",
    "StateMachine",
    "StateMirror",
    "TerminalConflict",
    "TextCrdt",
    "TextElement",
    "TextOp",
    "ThreadSafeContext",
    "TreeError",
    "TreeNode",
    "TreeNodeId",
    "TreeOp",
    "TreeOpId",
    "TreeUpdate",
    "TreeVersionFrontier",
    "WireStamp",
    "align",
    "applied_receipt",
    "assign_stable_keys",
    "async_slot",
    "batch",
    "batch_context",
    "benchmarks",
    "block_key",
    "byte_to_char",
    "cell",
    "cell_def",
    "command",
    "content_hash",
    "count_positive_fold",
    "crdt_plane",
    "crdt_registers",
    "decode_message",
    "effect",
    "encode_message",
    "ffi",
    "ffi_bytes_of",
    "in_batch",
    "ipc",
    "key_between",
    "kind_of",
    "lossless_tree_crdt",
    "normalize_ws",
    "projection",
    "reconcile_ops",
    "rejected_receipt",
    "run_benchmarks",
    "seqcrdt",
    "signal",
    "signal_def",
    "signaling",
    "similarity",
    "slot",
    "slot_def",
    "stable_id",
    "sum_fold",
    "textcrdt",
    "tree",
    "tree_update_from_wire",
    "tree_update_to_wire",
    "word_lcs_len",
]
__version__ = "0.17.0"

from . import (
    async_slot,
    benchmarks,
    command,
    crdt_plane,
    crdt_registers,
    ffi,
    ipc,
    lossless_tree_crdt,
    projection,
    seqcrdt,
    signaling,
    stable_id,
    textcrdt,
    tree,
)
from .async_effect import AsyncEffect, EffectEvent, EffectState
from .async_slot import AsyncSlot, SlotEvent, SlotState
from .batch import batch, batch_context, in_batch
from .benchmarks import Benchmark, BenchmarkResult, run_benchmarks
from .cell import Cell, CellSlot, cell, cell_def
from .collection import CellFamily, CellMap
from .command import (
    COMMAND_PLANE_FEATURE,
    CallState,
    CallStateKind,
    CommandApplyStatus,
    CommandCancel,
    CommandEvent,
    CommandEventKind,
    CommandEvents,
    CommandMessage,
    CommandPolicy,
    CommandProjection,
    CommandProjectionEntry,
    CommandProjectionImage,
    CommandRpcClient,
    CommandStatus,
    CommandSubmit,
    CommandTransport,
    DedupePolicy,
    StaleGeneration,
    TerminalConflict,
    applied_receipt,
    rejected_receipt,
)
from .crdt_plane import CrdtPlaneRuntime, PlaneEntry
from .crdt_registers import CellCrdt, LwwRegister, MvRegister, PnCounter
from .effect import Effect, effect
from .ffi import (
    FFI_HEADER_LEN,
    LazilyFfiBytes,
    LazilyFfiMessageKind,
    LazilyFfiStatus,
    decode_message,
    encode_message,
    ffi_bytes_of,
    kind_of,
)
from .ipc import (
    NODE_KEY_MAX_LEN,
    NODE_KEY_MAX_SEGMENTS,
    PROTOCOL_ID,
    PROTOCOL_MAJOR_VERSION,
    SHM_BLOB_HEADER_LEN,
    CapabilityHandshake,
    CausalReceipt,
    CausalReceipts,
    CrdtOp,
    CrdtSync,
    Delta,
    DeltaApplyStatus,
    DeltaOp,
    EdgeSnapshot,
    IpcMessage,
    IpcValue,
    NodeId,
    NodeKey,
    NodeKeyError,
    NodeSnapshot,
    NodeState,
    OpKind,
    PeerId,
    PeerPermissions,
    PermissionDenied,
    ReceiptApplyResult,
    ReceiptOutcome,
    ReceiptProjection,
    RemoteOp,
    ShmBlobArena,
    ShmBlobArenaError,
    ShmBlobRef,
    Snapshot,
    WireStamp,
)
from .lossless_tree_crdt import (
    LeafKind,
    LosslessTreeCrdt,
    NodeSeed,
    SeedElement,
    SeedLeaf,
    SortKey,
    TreeError,
    TreeNodeId,
    TreeOp,
    TreeOpId,
    TreeUpdate,
    TreeVersionFrontier,
    byte_to_char,
    key_between,
    tree_update_from_wire,
    tree_update_to_wire,
)
from .projection import StateMirror
from .reconciliation import Level, ReconcileOp, reconcile_ops
from .semtree import Fold, SemNode, SemTree, count_positive_fold, sum_fold
from .seqcrdt import SeqCrdt, SeqElement
from .signal import Signal, signal, signal_def
from .signaling import (
    PermissionMode,
    RoomCore,
    RoomError,
    SignalingFrame,
    SignalingFrameKind,
)
from .slot import BaseSlot, Slot, slot, slot_def
from .stable_id import (
    ANCHOR_PREFIX,
    CONTENT_PREFIX,
    Alignment,
    align,
    assign_stable_keys,
    block_key,
    content_hash,
    normalize_ws,
    similarity,
    word_lcs_len,
)
from .state_machine import StateMachine
from .statechart import ChartDef, StateChart
from .textcrdt import ROOT, OpId, TextCrdt, TextElement, TextOp
from .thread_safe import ThreadSafeContext
from .tree import CellTree, TreeNode
from .types import LazilyCallable
