"""
lazily — a lazy/reactive evaluation library for Python with context-aware
callable wrappers.

This package provides a simple and elegant way to implement lazy evaluation and
dependency injection patterns in Python applications. The core is the **Cell
kernel** (``#lzcellkernel``): a ``Source`` cell (value from outside; ``set`` /
``merge``) and a ``Computed`` cell (value from upstream, via a compute function),
with ``Effect`` the value-less sink outside the hierarchy. ``Cell`` is the value
node concept; ``Source`` is its native writable handle. Every cell is **guarded** (an equal
recompute suppresses the cascade); there is no unguarded derived mode —
``computed`` *is* the guarded derived constructor. The eager construction is
``computed(ctx, f).eager()``.

The :mod:`lazily.ipc` submodule implements the language-agnostic ``lazily-spec``
wire protocol (Snapshot / Delta) so a Python graph's state can be mirrored to
remote observers across processes and languages.
"""

__all__ = [
    "ANCHOR_PREFIX",
    "ARROW_DEFAULT_CAPACITY",
    "CONTENT_PREFIX",
    "FFI_HEADER_LEN",
    "IN_PROCESS_DEFAULT_CAPACITY",
    "NODE_KEY_MAX_LEN",
    "NODE_KEY_MAX_SEGMENTS",
    "PROTOCOL_ID",
    "PROTOCOL_MAJOR_VERSION",
    "ROOT",
    "SHM_BLOB_HEADER_LEN",
    "SHM_DEFAULT_CAPACITY",
    "Alignment",
    "ArrowBackend",
    "AsyncCellHandle",
    "AsyncCellMap",
    "AsyncComputeContext",
    "AsyncComputed",
    "AsyncComputedMap",
    "AsyncComputedState",
    "AsyncContext",
    "AsyncContextDisposedError",
    "AsyncDependencyMap",
    "AsyncEffect",
    "AsyncEffectHandle",
    "AsyncIngressCell",
    "AsyncLatestDurableProjection",
    "AsyncQueueCell",
    "AsyncReactiveMap",
    "AsyncSlot",
    "AsyncSlotHandle",
    "AsyncSlotMap",
    "AsyncSource",
    "AsyncSourceMap",
    "AsyncTeardownScope",
    "AsyncTopicCell",
    "AsyncWorkQueueCell",
    "AttrsBackend",
    "AwarenessCell",
    "BackpressurePolicy",
    "BarrierCell",
    "BarrierCore",
    "BaseSlot",
    "Benchmark",
    "BenchmarkResult",
    "BlobBackend",
    "BlobBackendKind",
    "BlobRouter",
    "BlobView",
    "BoundDim",
    "BoundHandle",
    "BreakerState",
    "BulkheadCell",
    "BulkheadCore",
    "CallState",
    "CallStateKind",
    "CapabilityHandshake",
    "CapabilityNegotiationResult",
    "CausalReceipt",
    "CausalReceipts",
    "Cell",
    "CellCrdt",
    "CellMap",
    "CellSlot",
    "CellTree",
    "ChartDef",
    "CircuitBreakerCell",
    "CircuitBreakerCore",
    "Clock",
    "CommandApplyStatus",
    "CommandCancel",
    "CommandEvent",
    "CommandEventKind",
    "CommandEvents",
    "CommandMessage",
    "CommandPolicy",
    "CommandProjection",
    "CommandProjectionEntry",
    "CommandProjectionImage",
    "CommandRpcClient",
    "CommandStatus",
    "CommandSubmit",
    "CommandTransport",
    "Compute",
    "ComputeEffect",
    "ComputeOps",
    "Computed",
    "ComputedMap",
    "Context",
    "CounterCell",
    "CrdtOp",
    "CrdtPlaneRuntime",
    "CrdtSync",
    "CrdtTree",
    "CronCell",
    "CronCore",
    "DataclassBackend",
    "DeadlineCell",
    "DeadlineCore",
    "DeadlineState",
    "Deadlined",
    "DebounceCell",
    "DebounceCore",
    "DedupePolicy",
    "Delta",
    "DeltaApplyStatus",
    "DeltaOp",
    "DependencyAvailability",
    "DependencyMap",
    "DiscoveryCell",
    "DiscoveryCore",
    "DisposedError",
    "DriverError",
    "Durable",
    "DurableOutbox",
    "EdgeSnapshot",
    "Effect",
    "EffectEvent",
    "EffectState",
    "EntryKind",
    "Ephemeral",
    "EphemeralCell",
    "EphemeralCore",
    "EphemeralMapCore",
    "EphemeralValue",
    "ExpiryPolicy",
    "Fold",
    "FramedTransport",
    "GaugeCell",
    "Health",
    "HealthCell",
    "HealthCore",
    "InMemoryOutbox",
    "InMemoryStore",
    "InProcIngress",
    "InProcTransport",
    "InProcessBackend",
    "Inbox",
    "IngressAdmission",
    "IngressAdmissionKind",
    "IngressAuthority",
    "IngressCell",
    "IngressChange",
    "IngressConfigError",
    "IngressCore",
    "IngressDropReason",
    "IngressEnvelope",
    "IngressError",
    "IngressLifecycle",
    "IngressOutcome",
    "IngressPolicy",
    "IngressReadiness",
    "IngressReceipt",
    "IngressReceiptChannel",
    "IngressReceiptOutcome",
    "IngressRetry",
    "IngressSchedule",
    "IngressScopeChange",
    "IngressScopeReaders",
    "IngressTransport",
    "IngressTransportKind",
    "IntervalCell",
    "IntervalCore",
    "IpcMessage",
    "IpcValue",
    "KeepLatest",
    "KeyAlreadyClaimedError",
    "KeyedFold",
    "KeyedFoldWriter",
    "KeyedRelay",
    "LatestDurableAck",
    "LatestDurableAckKind",
    "LatestDurableChange",
    "LatestDurableClaim",
    "LatestDurableClaimKind",
    "LatestDurableEnvelope",
    "LatestDurableFailure",
    "LatestDurableFailureKind",
    "LatestDurableKeyState",
    "LatestDurableProjection",
    "LatestDurableProjectionCore",
    "LatestDurableReconnect",
    "LatestDurableReconnectKind",
    "LatestDurableRevision",
    "LatestDurableSnapshot",
    "LatestDurableUpsert",
    "LatestDurableUpsertKind",
    "LazilyCallable",
    "LazilyFfiBytes",
    "LazilyFfiMessageKind",
    "LazilyFfiStatus",
    "Lcg",
    "LeaderCell",
    "LeaderRole",
    "LeafKind",
    "LeaseCell",
    "LeaseCore",
    "Level",
    "LockCell",
    "LosslessTreeCrdt",
    "LwwRegister",
    "ManualClock",
    "Max",
    "MembershipCell",
    "MembershipConfig",
    "MembershipCore",
    "MergeCell",
    "MergePolicy",
    "MetricFamily",
    "MetricFamilySnapshot",
    "MetricKind",
    "MetricNameError",
    "MetricSample",
    "MetricsRegistry",
    "MsgspecBackend",
    "MvRegister",
    "NamedTupleBackend",
    "NodeId",
    "NodeKey",
    "NodeKeyError",
    "NodeSeed",
    "NodeSnapshot",
    "NodeState",
    "NonDeterminismError",
    "OpId",
    "OpKind",
    "OrSet",
    "Outbox",
    "OutboxAck",
    "OutboxStore",
    "Overflow",
    "PeerChangeEvent",
    "PeerId",
    "PeerPermissions",
    "PeerSet",
    "PeerState",
    "PermissionDenied",
    "PermissionMode",
    "PhiAccrual",
    "PlaneEntry",
    "PnCounter",
    "PresenceCell",
    "PriorityStorage",
    "ProbabilisticSampleCell",
    "ProbabilisticSampleCore",
    "Progress",
    "PrometheusUnavailableError",
    "PydanticBackend",
    "QueueCell",
    "QueuePopError",
    "QueuePushError",
    "QueueReaderHandles",
    "QueueStorage",
    "RatePolicy",
    "RawFifo",
    "ReactiveCollector",
    "ReactiveMap",
    "ReadinessCell",
    "ReadinessCore",
    "ReceiptApplyResult",
    "ReceiptOutcome",
    "ReceiptProjection",
    "ReconcileOp",
    "RegistryOp",
    "RelayCell",
    "RelayConfigError",
    "RemoteOp",
    "ReplayRequest",
    "ResyncAction",
    "ResyncActionKind",
    "ResyncCoordinator",
    "ResyncRequest",
    "RetryPolicyCell",
    "RetryPolicyCore",
    "RevisionBarrier",
    "RevisionBarrierObservation",
    "RoomCore",
    "RoomError",
    "SampleCell",
    "SampleCore",
    "SampleMode",
    "SampleRng",
    "ScopeView",
    "SeedElement",
    "SeedLeaf",
    "SemNode",
    "SemTree",
    "SemaphoreCell",
    "SemaphoreCore",
    "SeqCrdt",
    "SeqElement",
    "SeqStamp",
    "ServiceRegistry",
    "ServiceRegistryCore",
    "SessionCell",
    "SessionCore",
    "SetUnion",
    "ShmBackend",
    "ShmBlobArena",
    "ShmBlobArenaError",
    "ShmBlobRef",
    "SignalingFrame",
    "SignalingFrameKind",
    "SlidingCell",
    "SlidingCore",
    "Slot",
    "SlotEvent",
    "SlotMap",
    "SlotState",
    "Snapshot",
    "SnapshotProvider",
    "SortKey",
    "Source",
    "SourceMap",
    "SourceSlot",
    "SourceTree",
    "SpillMode",
    "SpillPage",
    "SpillStore",
    "SqliteOutbox",
    "SqliteStore",
    "StaleComputeError",
    "StaleGeneration",
    "StateChart",
    "StateMachine",
    "StateMirror",
    "StoredOutbox",
    "StructBackend",
    "StructSource",
    "Sum",
    "SyncDriver",
    "TeardownScope",
    "TerminalConflict",
    "TextCrdt",
    "TextElement",
    "TextOp",
    "ThreadSafeCellMap",
    "ThreadSafeComputedMap",
    "ThreadSafeContext",
    "ThreadSafeDependencyMap",
    "ThreadSafeIngressCell",
    "ThreadSafeLatestDurableProjection",
    "ThreadSafeQueueCell",
    "ThreadSafeReactiveMap",
    "ThreadSafeSlotMap",
    "ThreadSafeSourceMap",
    "ThreadSafeTopicCell",
    "ThreadSafeWorkQueueCell",
    "ThrottleCell",
    "ThrottleCore",
    "ThrottleEdge",
    "TimelineSource",
    "Timeout",
    "TimeoutCell",
    "TimeoutCore",
    "TimeoutObservation",
    "TimeoutOperation",
    "Timer",
    "TimerCell",
    "TimerCore",
    "TimerError",
    "TimerObservation",
    "Transport",
    "TreeError",
    "TreeNode",
    "TreeNodeId",
    "TreeOp",
    "TreeOpId",
    "TreeUpdate",
    "TreeVersionFrontier",
    "TumblingCountCell",
    "TumblingCountCore",
    "TumblingTimeCell",
    "TumblingTimeCore",
    "UnsupportedStructError",
    "VecDequeStorage",
    "WindowPolicy",
    "WireLwwRegister",
    "WireStamp",
    "WorkQueueCell",
    "WorkQueueDeadLetter",
    "WorkQueueDeadLetterReason",
    "WorkQueueDelivery",
    "WorkQueueItem",
    "WorkQueueReaderHandles",
    "WorkflowClock",
    "WorkflowContext",
    "WorkflowScheduler",
    "align",
    "applied_receipt",
    "assign_stable_keys",
    "async_context",
    "async_effect",
    "async_reactive_family",
    "async_slot",
    "batch",
    "batch_context",
    "benchmarks",
    "block_key",
    "byte_to_char",
    "cell",
    "cell_def",
    "command",
    "compute",
    "computed",
    "computed_def",
    "computed_ripple_when",
    "content_hash",
    "coordination",
    "count_positive_fold",
    "count_upto",
    "crdt_plane",
    "crdt_registers",
    "crdt_tree",
    "decode_message",
    "deterministic_scope",
    "dispose_node",
    "effect",
    "encode_message",
    "eval_tracked",
    "ffi",
    "ffi_bytes_of",
    "format_metric_value",
    "in_batch",
    "ipc",
    "key_between",
    "keyed_fold",
    "kind_of",
    "lossless_tree_crdt",
    "membership",
    "merge_cell",
    "normalize_ws",
    "presence",
    "projection",
    "queue",
    "rateshape",
    "reconcile_ops",
    "register_metrics",
    "register_struct_backend",
    "rejected_receipt",
    "reliable_sync",
    "resilience",
    "resolve_struct_backend",
    "resolve_value",
    "run_benchmarks",
    "seqcrdt",
    "service",
    "signaling",
    "similarity",
    "slot",
    "slot_def",
    "source",
    "source_def",
    "spill_message",
    "spill_state",
    "spill_value",
    "stable_id",
    "stdlib",
    "struct_backends",
    "struct_source",
    "sum_fold",
    "teardown_scope",
    "temporal",
    "textcrdt",
    "thread_safe_reactive_family",
    "tracked_effect",
    "tree",
    "tree_update_from_wire",
    "tree_update_to_wire",
    "unregister_metrics",
    "windowing",
    "word_lcs_len",
    "workflow_context",
]
__version__ = "0.39.0"

import warnings
from typing import TYPE_CHECKING, Any

from . import (
    async_context,
    async_effect,
    async_reactive_family,
    async_slot,
    benchmarks,
    command,
    compute,
    coordination,
    crdt_plane,
    crdt_registers,
    crdt_tree,
    ffi,
    ipc,
    lossless_tree_crdt,
    membership,
    metrics,
    presence,
    projection,
    prometheus_egress,
    queue,
    rateshape,
    reliable_sync,
    resilience,
    seqcrdt,
    service,
    signaling,
    stable_id,
    stdlib,
    struct_cell,
    temporal,
    textcrdt,
    thread_safe_reactive_family,
    tree,
    windowing,
    workflow,
)
from .async_context import (
    AsyncCellHandle,
    AsyncComputeContext,
    AsyncComputed,
    AsyncComputedState,
    AsyncContext,
    AsyncContextDisposedError,
    AsyncEffectHandle,
    AsyncSlotHandle,
    AsyncSource,
    AsyncTeardownScope,
)
from .async_effect import AsyncEffect, EffectEvent, EffectState
from .async_reactive_family import (
    AsyncComputedMap,
    AsyncDependencyMap,
    AsyncReactiveMap,
    AsyncSourceMap,
)
from .async_slot import AsyncSlot, SlotEvent, SlotState
from .batch import batch, batch_context, in_batch
from .benchmarks import Benchmark, BenchmarkResult, run_benchmarks
from .cell import (
    Cell,
    CellSlot,
    Source,
    SourceSlot,
    cell,
    source,
    source_def,
)
from .collection import (
    ComputedMap,
    DependencyAvailability,
    DependencyMap,
    EntryKind,
    ReactiveMap,
    SourceMap,
)
from .command import (
    COMMAND_PLANE_FEATURE,
    CallState,
    CallStateKind,
    CommandApplyStatus,
    CommandCancel,
    CommandEvent,
    CommandEventKind,
    CommandEvents,
    CommandMessage,
    CommandPolicy,
    CommandProjection,
    CommandProjectionEntry,
    CommandProjectionImage,
    CommandRpcClient,
    CommandStatus,
    CommandSubmit,
    CommandTransport,
    DedupePolicy,
    StaleGeneration,
    TerminalConflict,
    applied_receipt,
    rejected_receipt,
)
from .compute import (
    BoundHandle,
    Compute,
    ComputeEffect,
    ComputeOps,
    Context,
    StaleComputeError,
    eval_tracked,
    tracked_effect,
)
from .coordination import (
    BarrierCell,
    BarrierCore,
    LeaderCell,
    LeaderRole,
    LeaseCell,
    LeaseCore,
    LockCell,
    SemaphoreCell,
    SemaphoreCore,
)
from .crdt_plane import CrdtPlaneRuntime, PlaneEntry
from .crdt_registers import CellCrdt, LwwRegister, MvRegister, PnCounter
from .crdt_tree import CrdtTree
from .effect import Effect, effect
from .ffi import (
    FFI_HEADER_LEN,
    LazilyFfiBytes,
    LazilyFfiMessageKind,
    LazilyFfiStatus,
    decode_message,
    encode_message,
    ffi_bytes_of,
    kind_of,
)
from .ingress import IngressCell, IngressScopeReaders
from .ingress_core import (
    IngressAdmission,
    IngressAdmissionKind,
    IngressAuthority,
    IngressChange,
    IngressConfigError,
    IngressCore,
    IngressDropReason,
    IngressEnvelope,
    IngressError,
    IngressLifecycle,
    IngressPolicy,
    IngressReadiness,
    IngressReceipt,
    IngressReceiptChannel,
    IngressReceiptOutcome,
    IngressRetry,
    IngressSchedule,
    IngressScopeChange,
    IngressTransport,
    IngressTransportKind,
    InProcIngress,
    ReplayRequest,
    ScopeView,
)
from .ingress_flavors import AsyncIngressCell, ThreadSafeIngressCell
from .ipc import (
    NODE_KEY_MAX_LEN,
    NODE_KEY_MAX_SEGMENTS,
    PROTOCOL_ID,
    PROTOCOL_MAJOR_VERSION,
    SHM_BLOB_HEADER_LEN,
    BlobBackendKind,
    CapabilityHandshake,
    CapabilityNegotiationResult,
    CausalReceipt,
    CausalReceipts,
    CrdtOp,
    CrdtSync,
    Delta,
    DeltaApplyStatus,
    DeltaOp,
    EdgeSnapshot,
    IpcMessage,
    IpcValue,
    NodeId,
    NodeKey,
    NodeKeyError,
    NodeSnapshot,
    NodeState,
    OpKind,
    OutboxAck,
    PeerId,
    PeerPermissions,
    PermissionDenied,
    ReceiptApplyResult,
    ReceiptOutcome,
    ReceiptProjection,
    RemoteOp,
    ResyncRequest,
    ShmBlobArena,
    ShmBlobArenaError,
    ShmBlobRef,
    Snapshot,
    WireStamp,
)
from .keyed_fold import (
    KeyAlreadyClaimedError,
    KeyedFold,
    KeyedFoldWriter,
    keyed_fold,
)
from .latest_durable_projection import (
    AsyncLatestDurableProjection,
    LatestDurableAck,
    LatestDurableAckKind,
    LatestDurableChange,
    LatestDurableClaim,
    LatestDurableClaimKind,
    LatestDurableEnvelope,
    LatestDurableFailure,
    LatestDurableFailureKind,
    LatestDurableKeyState,
    LatestDurableProjection,
    LatestDurableProjectionCore,
    LatestDurableReconnect,
    LatestDurableReconnectKind,
    LatestDurableRevision,
    LatestDurableSnapshot,
    LatestDurableUpsert,
    LatestDurableUpsertKind,
    ThreadSafeLatestDurableProjection,
)
from .lossless_tree_crdt import (
    LeafKind,
    LosslessTreeCrdt,
    NodeSeed,
    SeedElement,
    SeedLeaf,
    SortKey,
    TreeError,
    TreeNodeId,
    TreeOp,
    TreeOpId,
    TreeUpdate,
    TreeVersionFrontier,
    byte_to_char,
    key_between,
    tree_update_from_wire,
    tree_update_to_wire,
)
from .membership import (
    MembershipCell,
    MembershipConfig,
    MembershipCore,
    PeerChangeEvent,
    PeerSet,
    PeerState,
    PhiAccrual,
)
from .merge import (
    KeepLatest,
    Max,
    MergeCell,
    MergePolicy,
    RawFifo,
    SetUnion,
    Sum,
    merge_cell,
)
from .metrics import (
    CounterCell,
    GaugeCell,
    MetricFamily,
    MetricFamilySnapshot,
    MetricKind,
    MetricNameError,
    MetricSample,
    MetricsRegistry,
    format_metric_value,
)
from .presence import (
    AwarenessCell,
    Durable,
    Ephemeral,
    EphemeralCell,
    EphemeralCore,
    EphemeralMapCore,
    EphemeralValue,
    PresenceCell,
)
from .projection import StateMirror
from .prometheus_egress import (
    PrometheusUnavailableError,
    ReactiveCollector,
    register_metrics,
    unregister_metrics,
)
from .queue import (
    QueueCell,
    QueuePopError,
    QueuePushError,
    QueueReaderHandles,
    QueueStorage,
    TopicCell,
    TopicDurability,
    TopicSnapshot,
    TopicSubscribeOutcome,
    TopicSubscriptionSnapshot,
    VecDequeStorage,
)
from .queue_flavors import (
    AsyncQueueCell,
    AsyncTopicCell,
    AsyncWorkQueueCell,
    ThreadSafeQueueCell,
    ThreadSafeTopicCell,
    ThreadSafeWorkQueueCell,
)
from .rateshape import (
    DebounceCell,
    DebounceCore,
    Lcg,
    ProbabilisticSampleCell,
    ProbabilisticSampleCore,
    SampleCell,
    SampleCore,
    SampleMode,
    SampleRng,
    ThrottleCell,
    ThrottleCore,
    ThrottleEdge,
)
from .reconciliation import Level, ReconcileOp, reconcile_ops
from .relay import (
    BackpressurePolicy,
    BoundDim,
    ExpiryPolicy,
    FramedTransport,
    Inbox,
    IngressOutcome,
    InProcTransport,
    KeyedRelay,
    Outbox,
    Overflow,
    PriorityStorage,
    RatePolicy,
    RelayCell,
    RelayConfigError,
    SpillMode,
    SpillPage,
    SpillStore,
    Transport,
    WindowPolicy,
)
from .reliable_sync import (
    Clock,
    DriverError,
    DurableOutbox,
    InMemoryOutbox,
    InMemoryStore,
    OrSet,
    OutboxStore,
    Progress,
    ResyncAction,
    ResyncActionKind,
    ResyncCoordinator,
    SnapshotProvider,
    SqliteOutbox,
    SqliteStore,
    SyncDriver,
    WireLwwRegister,
)
from .reliable_sync import (
    Outbox as StoredOutbox,
)
from .resilience import (
    BreakerState,
    BulkheadCell,
    BulkheadCore,
    CircuitBreakerCell,
    CircuitBreakerCore,
    RetryPolicyCell,
    RetryPolicyCore,
    TimeoutCell,
    TimeoutCore,
)
from .semtree import Fold, SemNode, SemTree, count_positive_fold, sum_fold
from .seqcrdt import SeqCrdt, SeqElement, SeqStamp
from .service import (
    DiscoveryCell,
    DiscoveryCore,
    Health,
    HealthCell,
    HealthCore,
    ReadinessCell,
    ReadinessCore,
    RegistryOp,
    ServiceRegistry,
    ServiceRegistryCore,
)
from .signal import (
    Computed,
    computed,
    computed_def,
    computed_ripple_when,
)
from .signaling import (
    PermissionMode,
    RoomCore,
    RoomError,
    SignalingFrame,
    SignalingFrameKind,
)
from .slot import BaseSlot, DisposedError, Slot, cell_def, slot, slot_def
from .stable_id import (
    ANCHOR_PREFIX,
    CONTENT_PREFIX,
    Alignment,
    align,
    assign_stable_keys,
    block_key,
    content_hash,
    normalize_ws,
    similarity,
    word_lcs_len,
)
from .state_machine import StateMachine
from .statechart import ChartDef, StateChart
from .stdlib import (
    RevisionBarrier,
    RevisionBarrierObservation,
    Timeout,
    TimeoutObservation,
    TimeoutOperation,
    Timer,
    TimerError,
    TimerObservation,
)
from .struct_cell import (
    AttrsBackend,
    DataclassBackend,
    MsgspecBackend,
    NamedTupleBackend,
    PydanticBackend,
    StructBackend,
    StructSource,
    UnsupportedStructError,
    register_struct_backend,
    resolve_struct_backend,
    struct_backends,
    struct_source,
)
from .teardown import TeardownScope, dispose_node, teardown_scope
from .temporal import (
    CronCell,
    CronCore,
    DeadlineCell,
    DeadlineCore,
    Deadlined,
    DeadlineState,
    IntervalCell,
    IntervalCore,
    ManualClock,
    TimelineSource,
    TimerCell,
    TimerCore,
    count_upto,
)
from .textcrdt import ROOT, OpId, TextCrdt, TextElement, TextOp
from .thread_safe import ThreadSafeContext
from .thread_safe_reactive_family import (
    ThreadSafeComputedMap,
    ThreadSafeDependencyMap,
    ThreadSafeReactiveMap,
    ThreadSafeSourceMap,
)
from .transport import (
    ARROW_DEFAULT_CAPACITY,
    IN_PROCESS_DEFAULT_CAPACITY,
    SHM_DEFAULT_CAPACITY,
    ArrowBackend,
    BlobBackend,
    BlobRouter,
    BlobView,
    InProcessBackend,
    ShmBackend,
    resolve_value,
    spill_message,
    spill_state,
    spill_value,
)
from .tree import SourceTree, TreeNode
from .types import LazilyCallable
from .windowing import (
    SessionCell,
    SessionCore,
    SlidingCell,
    SlidingCore,
    TumblingCountCell,
    TumblingCountCore,
    TumblingTimeCell,
    TumblingTimeCore,
)
from .work_queue import (
    WorkQueueCell,
    WorkQueueDeadLetter,
    WorkQueueDeadLetterReason,
    WorkQueueDelivery,
    WorkQueueItem,
    WorkQueueReaderHandles,
)
from .workflow import (
    NonDeterminismError,
    WorkflowClock,
    WorkflowContext,
    WorkflowScheduler,
    deterministic_scope,
    workflow_context,
)


# ---------------------------------------------------------------------------
# Deprecated aliases (v2 kernel rename)
# ---------------------------------------------------------------------------
# The v2 kernel renamed the node kinds to ``Source`` and ``Computed``; the keyed
# collection types still said ``Cell`` / ``Slot``, a vocabulary the kernel no
# longer uses. ``SourceMap`` / ``ComputedMap`` (and the ThreadSafe / Async
# variants) and ``SourceTree`` now say which kind of entry they hold.
#
# A rename is not a removal: every old name stays importable. Reaching for one
# through the package root emits a :class:`DeprecationWarning` naming the
# replacement; the ``lazily.collection`` /
# ``lazily.thread_safe_reactive_family`` / ``lazily.async_reactive_family`` /
# ``lazily.tree`` submodules expose the same aliases without a warning.

#: Deprecated keyed-collection spelling -> its current name.
_DEPRECATED_ALIASES = {
    "AsyncCellMap": "AsyncSourceMap",
    "AsyncSlotMap": "AsyncComputedMap",
    "CellMap": "SourceMap",
    "CellTree": "SourceTree",
    "SlotMap": "ComputedMap",
    "ThreadSafeCellMap": "ThreadSafeSourceMap",
    "ThreadSafeSlotMap": "ThreadSafeComputedMap",
}

if TYPE_CHECKING:
    # Bound statically so a type checker still resolves the deprecated names;
    # at runtime they are served by ``__getattr__`` below so the access warns.
    AsyncCellMap = AsyncSourceMap
    AsyncSlotMap = AsyncComputedMap
    CellMap = SourceMap
    CellTree = SourceTree
    SlotMap = ComputedMap
    ThreadSafeCellMap = ThreadSafeSourceMap
    ThreadSafeSlotMap = ThreadSafeComputedMap


def __getattr__(name: str) -> Any:
    """Serve the deprecated keyed-collection names, warning once per access site."""
    current = _DEPRECATED_ALIASES.get(name)
    if current is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    warnings.warn(
        f"lazily.{name} is deprecated; use lazily.{current} instead. "
        "The v2 kernel renamed the node kinds to Source and Computed, so the "
        "keyed collections are SourceMap / ComputedMap / SourceTree.",
        DeprecationWarning,
        stacklevel=2,
    )
    return globals()[current]
