# @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
# Surface `delta` from schemas/delta.json,
# model sha256:cf7dfa4e63bdb67441babc61f7e861b18cb1a9d822ca8e6b8757d66ce943b5e7.
# Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.
# fmt: off
"""Generated wire types for the `delta` surface."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from ._delta_semantics import DeltaOpSemantics, DeltaSemantics, IpcValueSemantics
from ._wire_scalars import NodeKey, ShmBlobRef


_U64_MAX = 0xFFFF_FFFF_FFFF_FFFF


def _wire_object(name: str, value: Any, fields: tuple[str, ...]) -> dict[str, Any]:
    """Return ``value`` as a wire object whose keys are exactly ``fields``."""
    if not isinstance(value, dict):
        raise ValueError(f"{name}: expected an object, got {value!r}")
    missing = [key for key in fields if key not in value]
    if missing:
        raise ValueError(f"{name}: missing field {missing[0]!r}")
    unknown = sorted(key for key in value if key not in fields)
    if unknown:
        raise ValueError(f"{name}: unknown field {unknown[0]!r}")
    return value


def _wire_object_opt(
    name: str, value: Any, required: tuple[str, ...], optional: tuple[str, ...]
) -> dict[str, Any]:
    """Return ``value`` as a wire object: every ``required`` key, any ``optional`` ones."""
    if not isinstance(value, dict):
        raise ValueError(f"{name}: expected an object, got {value!r}")
    missing = [key for key in required if key not in value]
    if missing:
        raise ValueError(f"{name}: missing field {missing[0]!r}")
    unknown = sorted(key for key in value if key not in required and key not in optional)
    if unknown:
        raise ValueError(f"{name}: unknown field {unknown[0]!r}")
    return value


def _wire_str(name: str, value: Any) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{name}: expected a string, got {value!r}")
    return value


def _wire_u64(name: str, value: Any) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name}: expected an unsigned integer, got {value!r}")
    return value


def _wire_bytes(name: str, value: Any) -> bytes:
    if not isinstance(value, list) or not all(
        isinstance(b, int) and not isinstance(b, bool) and 0 <= b <= 255 for b in value
    ):
        raise ValueError(f"{name}: expected an array of bytes (0..=255), got {value!r}")
    return bytes(value)


def _wire_list(name: str, value: Any) -> list[Any]:
    if not isinstance(value, list):
        raise ValueError(f"{name}: expected an array, got {value!r}")
    return value


class DeltaOp(DeltaOpSemantics):
    """One incremental graph mutation. Externally tagged: a single-key object whose key is
    the PascalCase variant name.
    """

    __slots__ = ()

    def to_wire(self) -> Any:  # pragma: no cover - every variant overrides it
        raise NotImplementedError

    @staticmethod
    def from_wire(value: Any) -> DeltaOp:
        """Decode strictly: exactly one known, externally-tagged variant."""
        if not isinstance(value, dict) or len(value) != 1:
            raise ValueError(f"DeltaOp: expected a single-key object, got {value!r}")
        ((tag, body),) = value.items()
        if tag == "CellSet":
            return DeltaOp_CellSet._from_body(body)
        if tag == "SlotValue":
            return DeltaOp_SlotValue._from_body(body)
        if tag == "Invalidate":
            return DeltaOp_Invalidate._from_body(body)
        if tag == "NodeAdd":
            return DeltaOp_NodeAdd._from_body(body)
        if tag == "NodeRemove":
            return DeltaOp_NodeRemove._from_body(body)
        if tag == "EdgeAdd":
            return DeltaOp_EdgeAdd._from_body(body)
        if tag == "EdgeRemove":
            return DeltaOp_EdgeRemove._from_body(body)
        if tag == "QueuePush":
            return DeltaOp_QueuePush._from_body(body)
        if tag == "QueuePop":
            return DeltaOp_QueuePop._from_body(body)
        if tag == "QueueClose":
            return DeltaOp_QueueClose._from_body(body)
        raise ValueError(f"unknown DeltaOp variant: {tag!r}")


@dataclass(frozen=True, slots=True)
class DeltaOp_CellSet(DeltaOp):
    """A source cell was changed to `payload`."""

    node: NodeId
    """Target node."""
    payload: IpcValue
    """Value, inline or by blob descriptor."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
            "payload": self.payload.to_wire(),
        }
        return {"CellSet": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_CellSet:
        d = _wire_object_opt("DeltaOp.CellSet", value, ("node", "payload"), ())
        return cls(
            node=_wire_u64("DeltaOp.CellSet.node", d["node"]),
            payload=IpcValue.from_wire(d["payload"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_SlotValue(DeltaOp):
    """A lazily recomputed slot published a concrete value."""

    node: NodeId
    """Target node."""
    payload: IpcValue
    """Value, inline or by blob descriptor."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
            "payload": self.payload.to_wire(),
        }
        return {"SlotValue": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_SlotValue:
        d = _wire_object_opt("DeltaOp.SlotValue", value, ("node", "payload"), ())
        return cls(
            node=_wire_u64("DeltaOp.SlotValue.node", d["node"]),
            payload=IpcValue.from_wire(d["payload"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_Invalidate(DeltaOp):
    """A node was dirtied without publishing a concrete value."""

    node: NodeId
    """Target node."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
        }
        return {"Invalidate": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_Invalidate:
        d = _wire_object_opt("DeltaOp.Invalidate", value, ("node",), ())
        return cls(
            node=_wire_u64("DeltaOp.Invalidate.node", d["node"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_NodeAdd(DeltaOp):
    """A new node became visible."""

    node: NodeId
    """New node."""
    type_tag: str
    """Binding-defined type tag of the new node."""
    state: NodeState
    """Initial node body."""
    key: NodeKey | None = None
    """Optional wire-stable keyed address. A conforming ENCODER omits it when absent; an
    explicit null is also wire-valid and a decoder MUST read both forms as absent
    (protocol.md § NodeKey, #lzkeynullstrict). This carried a bare NodeKey $ref until
    that audit, which made a frame the spec now requires decoders to accept
    schema-invalid.
    """

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
            "type_tag": self.type_tag,
            "state": self.state.to_wire(),
        }
        if self.key is not None:
            body["key"] = None if self.key is None else self.key.to_wire()
        return {"NodeAdd": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_NodeAdd:
        d = _wire_object_opt("DeltaOp.NodeAdd", value, ("node", "type_tag", "state"), ("key",))
        return cls(
            node=_wire_u64("DeltaOp.NodeAdd.node", d["node"]),
            type_tag=_wire_str("DeltaOp.NodeAdd.type_tag", d["type_tag"]),
            state=NodeState.from_wire(d["state"]),
            key=None if d.get("key") is None else NodeKey.from_wire(d.get("key")),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_NodeRemove(DeltaOp):
    """A node was removed."""

    node: NodeId
    """Target node."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
        }
        return {"NodeRemove": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_NodeRemove:
        d = _wire_object_opt("DeltaOp.NodeRemove", value, ("node",), ())
        return cls(
            node=_wire_u64("DeltaOp.NodeRemove.node", d["node"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_EdgeAdd(DeltaOp):
    """A dependency edge was added."""

    dependent: NodeId
    """Node that reads `dependency`."""
    dependency: NodeId
    """Node read by `dependent`."""

    def __post_init__(self) -> None:
        if not 0 <= self.dependent <= _U64_MAX:
            raise ValueError(f"dependent must be in 0..=2^64-1, got {self.dependent}")
        if not 0 <= self.dependency <= _U64_MAX:
            raise ValueError(f"dependency must be in 0..=2^64-1, got {self.dependency}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "dependent": self.dependent,
            "dependency": self.dependency,
        }
        return {"EdgeAdd": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_EdgeAdd:
        d = _wire_object_opt("DeltaOp.EdgeAdd", value, ("dependent", "dependency"), ())
        return cls(
            dependent=_wire_u64("DeltaOp.EdgeAdd.dependent", d["dependent"]),
            dependency=_wire_u64("DeltaOp.EdgeAdd.dependency", d["dependency"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_EdgeRemove(DeltaOp):
    """A dependency edge was removed."""

    dependent: NodeId
    """Node that reads `dependency`."""
    dependency: NodeId
    """Node read by `dependent`."""

    def __post_init__(self) -> None:
        if not 0 <= self.dependent <= _U64_MAX:
            raise ValueError(f"dependent must be in 0..=2^64-1, got {self.dependent}")
        if not 0 <= self.dependency <= _U64_MAX:
            raise ValueError(f"dependency must be in 0..=2^64-1, got {self.dependency}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "dependent": self.dependent,
            "dependency": self.dependency,
        }
        return {"EdgeRemove": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_EdgeRemove:
        d = _wire_object_opt("DeltaOp.EdgeRemove", value, ("dependent", "dependency"), ())
        return cls(
            dependent=_wire_u64("DeltaOp.EdgeRemove.dependent", d["dependent"]),
            dependency=_wire_u64("DeltaOp.EdgeRemove.dependency", d["dependency"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_QueuePush(DeltaOp):
    """Op-log delta form for a QueueCell node: append `payload` to the tail. The op-log
    delta is the incremental counterpart to the storage-snapshot form (cell-model.md §
    Wire and snapshot shape); a run of same-direction QueuePush ops fuses into one
    multi-epoch batch Delta (protocol.md § Backpressure & outbox coalescing).
    """

    node: NodeId
    """Target node."""
    payload: IpcValue
    """Value, inline or by blob descriptor."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
            "payload": self.payload.to_wire(),
        }
        return {"QueuePush": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_QueuePush:
        d = _wire_object_opt("DeltaOp.QueuePush", value, ("node", "payload"), ())
        return cls(
            node=_wire_u64("DeltaOp.QueuePush.node", d["node"]),
            payload=IpcValue.from_wire(d["payload"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_QueuePop(DeltaOp):
    """Op-log delta form for a QueueCell node: remove the head. Carries no value (the
    popped element is determined by ordered replay); a re-delivered pop is Ignored by
    the epoch gap rule. Crosses the wire only when consumption is authoritatively
    replicated (mirror sync); in the default producer→consumer sync the remote
    consumer's pops are local. A QueuePop/QueueClose is a fusion boundary
    (order-sensitive).
    """

    node: NodeId
    """Target node."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
        }
        return {"QueuePop": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_QueuePop:
        d = _wire_object_opt("DeltaOp.QueuePop", value, ("node",), ())
        return cls(
            node=_wire_u64("DeltaOp.QueuePop.node", d["node"]),
        )


@dataclass(frozen=True, slots=True)
class DeltaOp_QueueClose(DeltaOp):
    """Op-log delta form for a QueueCell node: mark closed (idempotent, terminal — Closed
    is distinct from Empty). A fusion boundary.
    """

    node: NodeId
    """Target node."""

    def __post_init__(self) -> None:
        if not 0 <= self.node <= _U64_MAX:
            raise ValueError(f"node must be in 0..=2^64-1, got {self.node}")

    def to_wire(self) -> dict[str, Any]:
        body: dict[str, Any] = {
            "node": self.node,
        }
        return {"QueueClose": body}

    @classmethod
    def _from_body(cls, value: Any) -> DeltaOp_QueueClose:
        d = _wire_object_opt("DeltaOp.QueueClose", value, ("node",), ())
        return cls(
            node=_wire_u64("DeltaOp.QueueClose.node", d["node"]),
        )


_DELTA_FIELDS = ("base_epoch", "epoch", "ops")


@dataclass(frozen=True, slots=True)
class Delta(DeltaSemantics):
    """Incremental change set: ordered ops that take the receiver from `base_epoch` to
    `epoch`.
    """

    base_epoch: int
    """Epoch this delta applies to (must equal the receiver's last_epoch)."""
    epoch: int
    """New epoch, >= base_epoch + 1. Usually base_epoch + 1; a multi-epoch-span delta has
    epoch > base_epoch + 1 (epoch - base_epoch = accepted-event span). See protocol.md §
    Multi-epoch-span delta.
    """
    ops: list[DeltaOp] = field(default_factory=list)
    """Ordered operations."""

    def __post_init__(self) -> None:
        if not 0 <= self.base_epoch <= _U64_MAX:
            raise ValueError(f"base_epoch must be in 0..=2^64-1, got {self.base_epoch}")
        if not 0 <= self.epoch <= _U64_MAX:
            raise ValueError(f"epoch must be in 0..=2^64-1, got {self.epoch}")

    def to_wire(self) -> dict[str, Any]:
        return {
            "base_epoch": self.base_epoch,
            "epoch": self.epoch,
            "ops": [item.to_wire() for item in self.ops],
        }

    @classmethod
    def from_wire(cls, value: Any) -> Delta:
        """Decode strictly: exactly the declared keys, each well-typed."""
        d = _wire_object("Delta", value, _DELTA_FIELDS)
        return cls(
            base_epoch=_wire_u64("Delta.base_epoch", d["base_epoch"]),
            epoch=_wire_u64("Delta.epoch", d["epoch"]),
            ops=[DeltaOp.from_wire(item) for item in _wire_list("Delta.ops", d["ops"])],
        )


#: Wire-stable node identifier (u64). The full u64 range is wire-valid; the 2^53-1 bound
#: is a PRODUCER obligation on peers whose runtime represents integers as IEEE-754
#: doubles, and a decoder that cannot represent a received value exactly MUST reject the
#: frame rather than round it (protocol.md § NodeId / PeerId, #lzspecdecoderbound).
#: Schema validity is therefore u64-wide — a narrower binding refuses at decode, not
#: here.
NodeId = int


class IpcValue(IpcValueSemantics):
    """Externally-tagged delta payload: inline bytes or a shared-memory blob reference.
    """

    __slots__ = ()

    def to_wire(self) -> Any:  # pragma: no cover - every variant overrides it
        raise NotImplementedError

    @staticmethod
    def from_wire(value: Any) -> IpcValue:
        """Decode strictly: exactly one known, externally-tagged variant."""
        if not isinstance(value, dict) or len(value) != 1:
            raise ValueError(f"IpcValue: expected a single-key object, got {value!r}")
        ((tag, body),) = value.items()
        if tag == "Inline":
            return IpcValue_Inline._from_body(body)
        if tag == "SharedBlob":
            return IpcValue_SharedBlob._from_body(body)
        raise ValueError(f"unknown IpcValue variant: {tag!r}")


@dataclass(frozen=True, slots=True)
class IpcValue_Inline(IpcValue):
    """Inline serialized bytes as JSON array of u8 (NOT base64)."""

    data: bytes

    def to_wire(self) -> dict[str, Any]:
        return {"Inline": list(self.data)}

    @classmethod
    def _from_body(cls, value: Any) -> IpcValue_Inline:
        return cls(data=_wire_bytes("IpcValue.Inline", value))


@dataclass(frozen=True, slots=True)
class IpcValue_SharedBlob(IpcValue):
    """Value stored in a blob backend, by descriptor."""

    blob: ShmBlobRef

    def to_wire(self) -> dict[str, Any]:
        return {"SharedBlob": self.blob.to_wire()}

    @classmethod
    def _from_body(cls, value: Any) -> IpcValue_SharedBlob:
        return cls(blob=ShmBlobRef.from_wire(value))


class NodeState:
    """Externally-tagged node body: concrete bytes, a shared-memory value, or an opaque
    (visible but non-serializable) node.
    """

    __slots__ = ()

    def to_wire(self) -> Any:  # pragma: no cover - every variant overrides it
        raise NotImplementedError

    @staticmethod
    def from_wire(value: Any) -> NodeState:
        """Decode strictly: exactly one known, externally-tagged variant."""
        if isinstance(value, str):
            if value == "Opaque":
                return NodeState_Opaque()
            raise ValueError(f"unknown NodeState unit variant: {value!r}")
        if not isinstance(value, dict) or len(value) != 1:
            raise ValueError(f"NodeState: expected a single-key object, got {value!r}")
        ((tag, body),) = value.items()
        if tag == "Payload":
            return NodeState_Payload._from_body(body)
        if tag == "SharedBlob":
            return NodeState_SharedBlob._from_body(body)
        raise ValueError(f"unknown NodeState variant: {tag!r}")


@dataclass(frozen=True, slots=True)
class NodeState_Payload(NodeState):
    """Serialized value bytes as JSON array of u8 (NOT base64)."""

    data: bytes

    def to_wire(self) -> dict[str, Any]:
        return {"Payload": list(self.data)}

    @classmethod
    def _from_body(cls, value: Any) -> NodeState_Payload:
        return cls(data=_wire_bytes("NodeState.Payload", value))


@dataclass(frozen=True, slots=True)
class NodeState_SharedBlob(NodeState):
    """Value stored in a blob backend, by descriptor."""

    blob: ShmBlobRef

    def to_wire(self) -> dict[str, Any]:
        return {"SharedBlob": self.blob.to_wire()}

    @classmethod
    def _from_body(cls, value: Any) -> NodeState_SharedBlob:
        return cls(blob=ShmBlobRef.from_wire(value))


@dataclass(frozen=True, slots=True)
class NodeState_Opaque(NodeState):
    """Visible but non-serializable node: no body crosses the wire."""

    def to_wire(self) -> str:
        return "Opaque"
