# @generated by lazily-spec scripts/wire_codegen.py. DO NOT EDIT.
# Surface `receipts` from schemas/receipts.json,
# model sha256:faf31f5c1db054295114b513d51ae6d4b7b47658147cf8044838340a72946b87.
# Regenerate from lazily-spec with `make wire-codegen`; semantics stay hand-written.
# fmt: off
"""Generated wire types for the `receipts` surface."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from ._receipt_semantics import CausalReceiptsSemantics, ReceiptOutcomeSemantics


_U64_MAX = 0xFFFF_FFFF_FFFF_FFFF


def _wire_object(name: str, value: Any, fields: tuple[str, ...]) -> dict[str, Any]:
    """Return ``value`` as a wire object whose keys are exactly ``fields``."""
    if not isinstance(value, dict):
        raise ValueError(f"{name}: expected an object, got {value!r}")
    missing = [key for key in fields if key not in value]
    if missing:
        raise ValueError(f"{name}: missing field {missing[0]!r}")
    unknown = sorted(key for key in value if key not in fields)
    if unknown:
        raise ValueError(f"{name}: unknown field {unknown[0]!r}")
    return value


def _wire_str(name: str, value: Any) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{name}: expected a string, got {value!r}")
    return value


def _wire_u64(name: str, value: Any) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise ValueError(f"{name}: expected an unsigned integer, got {value!r}")
    return value


def _wire_list(name: str, value: Any) -> list[Any]:
    if not isinstance(value, list):
        raise ValueError(f"{name}: expected an array, got {value!r}")
    return value


class ReceiptOutcome(ReceiptOutcomeSemantics, Enum):
    """Outcome vocabulary. observed/accepted are non-terminal; applied/rejected are
    terminal.
    """

    OBSERVED = "observed"
    """A peer/process observed the causation request."""
    ACCEPTED = "accepted"
    """A peer/process accepted or queued the request."""
    APPLIED = "applied"
    """The requested effect/state change was applied."""
    REJECTED = "rejected"
    """The requested effect/state change was rejected."""

    @classmethod
    def from_wire(cls, value: Any) -> ReceiptOutcome:
        """Parse a wire string, rejecting unknown values."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(
            f"unknown ReceiptOutcome: {value!r} (expected one of observed/accepted/applied/rejected)"
        )

    def to_wire(self) -> str:
        return self.value


_CAUSAL_RECEIPT_FIELDS = (
    "receipt_id",
    "causation_id",
    "observer",
    "generation",
    "outcome",
    "reason",
    "payload_hash",
)


@dataclass(frozen=True, slots=True)
class CausalReceipt:
    """One receipt event for a command/effect causation id."""

    receipt_id: str
    """Idempotency key for this receipt event."""
    causation_id: str
    """Stable id of the command, event, or effect request this receipt observes."""
    observer: str
    """Peer, process, or subsystem that produced the receipt."""
    generation: int
    """Producer/editor generation. Consumers discard receipts outside the current
    generation for the causation id.
    """
    outcome: ReceiptOutcome
    """Receipt outcome."""
    reason: str | None = None
    """Optional human/debug rejection reason."""
    payload_hash: str | None = None
    """Optional hash of the state/payload observed by the receipt."""

    def __post_init__(self) -> None:
        if len(self.receipt_id) < 1:
            raise ValueError("receipt_id must be a non-empty string")
        if len(self.causation_id) < 1:
            raise ValueError("causation_id must be a non-empty string")
        if len(self.observer) < 1:
            raise ValueError("observer must be a non-empty string")
        if not 0 <= self.generation <= _U64_MAX:
            raise ValueError(f"generation must be in 0..=2^64-1, got {self.generation}")

    def to_wire(self) -> dict[str, Any]:
        return {
            "receipt_id": self.receipt_id,
            "causation_id": self.causation_id,
            "observer": self.observer,
            "generation": self.generation,
            "outcome": self.outcome.to_wire(),
            "reason": self.reason,
            "payload_hash": self.payload_hash,
        }

    @classmethod
    def from_wire(cls, value: Any) -> CausalReceipt:
        """Decode strictly: exactly the declared keys, each well-typed."""
        d = _wire_object("CausalReceipt", value, _CAUSAL_RECEIPT_FIELDS)
        return cls(
            receipt_id=_wire_str("CausalReceipt.receipt_id", d["receipt_id"]),
            causation_id=_wire_str("CausalReceipt.causation_id", d["causation_id"]),
            observer=_wire_str("CausalReceipt.observer", d["observer"]),
            generation=_wire_u64("CausalReceipt.generation", d["generation"]),
            outcome=ReceiptOutcome.from_wire(d["outcome"]),
            reason=None if d["reason"] is None else _wire_str("CausalReceipt.reason", d["reason"]),
            payload_hash=None if d["payload_hash"] is None else _wire_str("CausalReceipt.payload_hash", d["payload_hash"]),
        )


_CAUSAL_RECEIPTS_FIELDS = ("receipts",)


@dataclass(frozen=True, slots=True)
class CausalReceipts(CausalReceiptsSemantics):
    """Wire body for the externally-tagged `CausalReceipts` envelope."""

    receipts: list[CausalReceipt] = field(default_factory=list)
    """Receipt batch."""

    def to_wire(self) -> dict[str, Any]:
        """Encode the externally-tagged ``CausalReceipts`` frame."""
        body = {
            "receipts": [item.to_wire() for item in self.receipts],
        }
        return {"CausalReceipts": body}

    @classmethod
    def from_wire(cls, value: Any) -> CausalReceipts:
        """Decode the externally-tagged ``CausalReceipts`` frame strictly."""
        tagged = _wire_object("ReceiptMessage", value, ("CausalReceipts",))
        d = _wire_object("CausalReceipts", tagged["CausalReceipts"], _CAUSAL_RECEIPTS_FIELDS)
        return cls(
            receipts=[CausalReceipt.from_wire(item) for item in _wire_list("CausalReceipts.receipts", d["receipts"])],
        )
